### ISSUE TITLE
set mFlags  when init header

### ISSUE THREAD

**Issue by huxinxin** [VolantMQ/vlapi#4]
@troian Hello, thanks for this great api.I'm not sure if it is necessary to set mFlags in "head.init" function of package "mqttp" as following:

    func (h *header) init(t Type, v ProtocolVersion, sz func() int, enc, dec func([]byte) (int, error)) {
        h.mType = t
        h.version = v
        h.cb.encode = enc
        h.cb.decode = dec
        h.cb.size = sz

        // set the mFlags
        if h.mType == PUBREL || h.mType == SUBSCRIBE || h.mType == UNSUBSCRIBE {
            h.mFlags = 2
        }
        if v >= ProtocolV50 {
            h.properties.reset()
        }
    }

**Comment by troian** [comment]
@huxinxin thanks. fixed
